---
num_iterations: [20]
product_share_reform_values: [0.5]
product_share_sales_values: [1]
ed_reduction_values: [5, 10]
unhealthy_sales_change_values: [5, 10, 15] # percentage shift in sales
healthy_sales_change_values: [5, 10, 15] # percentage shift in sales
