---
num_iterations: [20]
product_share_reform_values_low: [1] # percentage of HFSS products that are reformulated to become non-HFSS
product_share_reform_values_medium: [0.5] # percentage of HFSS products that are reformulated to become non-HFSS
product_share_reform_values_high: [0.25] # percentage of HFSS products that are reformulated to become non-HFSS
hfss_high_sales_change_values: [10, 15] # percentage shift in sales
hfss_low_sales_change_values: [1, 2.5] # percentage shift in sales
hfss_cutoff: [8, 15, 20]
product_share_sale_values: [1]
