---
num_iterations: [100]
product_share_reform_values_low: [1] # percentage of HFSS products that are reformulated to become non-HFSS
product_share_reform_values_medium: [0.5] # percentage of HFSS products that are reformulated to become non-HFSS
product_share_reform_values_high: [0.25] # percentage of HFSS products that are reformulated to become non-HFSS
hfss_high_sales_change_values: [12.5] # percentage shift in sales
hfss_low_sales_change_values: [2.5] # percentage shift in sales
product_share_sale_values: [1] # share of products with sales change
hfss_cutoff: [8, 15, 20]
