---
num_iterations: [20]
product_share_reform_values: [0.5]
product_share_sales_values: [1]
npm_decrease_values: [1, 2, 3, 4, 5]
unhealthy_sales_change_values: [2.5, 5, 10] # percentage shift in sales
healthy_sales_change_values: [2.5, 5, 10] # percentage shift in sales
