---
num_iterations: [20]
product_share_reform_values: [0.5]
product_share_sales_values: [1]
npm_decrease_values: [5, 6, 7]
unhealthy_sales_change_values: [10, 12.5, 15] # percentage shift in sales
healthy_sales_change_values: [10, 12.5, 15] # percentage shift in sales
