---
num_iterations: [1000]
product_share_reform_values: [0.5]
product_share_sales_values: [1]
npm_decrease_values: [3]
unhealthy_sales_change_values: [7] # percentage shift in sales
healthy_sales_change_values: [5] # percentage shift in sales
